export * from './assets/assets.component';
export * from './assets/assets.route';
export * from './mutual-fund/mutual-fund.component';
export * from './mutual-fund/mutual-fund.route';
export * from './my-assets.route';
export * from './assets/mutual-fund.service';
export * from './assets/stocks.service';
export * from './my-assets.module';
export * from './assets/assets.service';
